config/routes.rb
Rails.application.routes.draw do
  resources :orders, :items
  devise_for :customers
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get '/cart', to: "items#cart", as: "cart"
  get '/checkout', to: "orders#new", as: "check_out"
  get '/cart/remove', to: "items#remove_cookie"
  get '/forbidden', to: 'welcome#forbidden', as: 'forbidden'
  get '/admin', to: "admin#index"

  get '/admin/items', to: "admin#items"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, :dependent => :destroy

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_customer!, only: [:new]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(available: :true)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new

  end

  # GET /items/1/edit
  def edit
  end


  def remove_cookie
    logger.warn "DELETING COOKIE"
    cookie_id = "item_" + params[:cookieIndex]
    logger.warn(cookie_id)
    logger.warn(cookies[cookie_id])
    cookies.delete cookie_id
    redirect_to :cart
  end

  def cart
    @items = Array.new
    @items = get_cart_items
    puts "Items in array: "
    puts @items
    puts "Cart total: "
    puts get_cart_total
    @total = get_cart_total
  end




  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item = Item.new

    respond_to do |format|
      if @item.save
        if params[:images]
          params[:images].each { |image|
              @item.images.create(file: image)
            }
          end
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:name, :description, :price, :picture, :total, :notes, :customer, :item_status_id, :available)
    params.permit(:images)
  end
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/views/items/.cart.html.erb
<table class="table">
  <thead>
  <tr>
    <td>Name</td>
    <td>Price</td>
    <td>Quantity</td>
  </tr>
  </thead>

<% @cart_items.each_with_index do |cart_item, index| %>
    <tr>
      <td><%=cart_item[:item].name%></td>
      <td><%=cart_item[:item].price%></td>
      <td><%=cart_item[:qty]%></td>
      <td><a href="/cart/remove?cookieIndex=<%= cart_item[:item].id %>" >Remove from Cart</div></td>

    </tr>
<% end %>
</table>
<form>

<%= link_to "Check Out", check_out_path %>

app/views/items/.index.html.erb
      <div class="row">
      <% @items.each do |item| %>
            <div class="col-sm-4 item">
            <%= link_to item do  %>

              <div class="clearfix grpelem" id="pu1373"><!-- column -->
                <div class="colelem" id="u1373"><!-- simple frame --></div>
                <div class="clearfix colelem" id="u734-4" data-muse-temp-textContainer-sizePolicy="true" data-muse-temp-textContainer-pinning="true"><!-- content -->
                  <%= image_tag "placeholderbasket", height: 150 %>
                  <p><%= item.name %></p>
                  <p>$<%= item.price %></p>
                </div>
              </div>

          <% end %>
            </div>
            <% end %>
      </div>
  </div>
  <div class="verticalspacer" data-offset-top="999" data-content-above-spacer="999" data-content-below-spacer="168" data-sizePolicy="fixed" data-pintopage="page_fixedLeft"></div>
  <div class="clearfix grpelem" id="pu1403-4"><!-- column -->
    <a class="nonblock nontext transition clearfix colelem" id="u1403-4" href="contact.html" data-muse-temp-textContainer-sizePolicy="true" data-muse-temp-textContainer-pinning="true"><!-- content --><p>CONTACT</p></a>
    <div class="browser_width colelem" id="u923-bw">
      <div id="u923"><!-- group -->
        <div class="clearfix" id="u923_align_to_page">
          <div class="clearfix grpelem" id="u399-4" data-muse-temp-textContainer-sizePolicy="true" data-muse-temp-textContainer-pinning="true"><!-- content -->
            <p>Website Created By Xaas</p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/items/.show.html.erb
<%= hidden_field :item, :id , { value: @item.id, id: 'item' } %>
<div class="row">
  <div class="col-sm-6">
  <%= image_tag @item.picture %>
  </div>
  <div class="col-sm-6 item">
    <h2><%= @item.name %></h2>
    <h4><%= @item.price %></h4>
    <label for="">Quantity</label>
    <input type="number" id="qty" value="1"/>
    <div class="btn-primary button" id="addToCart">Add to Shopping Cart</div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, id: "order-form", multipart: true) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
    <div>
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>
    <div class="dropzone">
      <%= form.label :image %>
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
    <% if current_customer.try(:admin?) %>
    <%= form.label :availabilty %>
    <%= form.check_box :available %>
  <% end %>

    <div>
      <%= form.label :submit %>
      <%= form.submit  %>
    </div>
<% end %>

app/views/items/cart.haml
.spacer
.container
  .row.card.table-card
    %table.table
      %thead
        %tr
          %th Name
          %th Price
          %th Quantity
          %th
      - @cart_items.each_with_index do |cart_item, index|
        %tr
          %td= cart_item[:item].name
          %td= number_to_currency(cart_item[:item].price)
          %td= cart_item[:qty]
          %td
            %a{:href => "/cart/remove?cookieIndex=#{cart_item[:item].id}"}
              %i.fa.fa-trash-o
  .spacer
  .row
    .col-md-1
    .col-md-4
      %h6
        = "Order Total: #{number_to_currency(@total)}"
    .col-md-4
    .col-md-3
      = link_to "Proceed to checkout", check_out_path, class: 'button btn btn-primary'

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.haml
.spacer
.container
  .row
    - @items.each do |item|
      = link_to item, class: 'card shop-card' do
        = image_tag item.picture, class: 'item-image'
        %p.card-text
          = item.name
        %p.card-text
          #{number_to_currency(item.price)}

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.haml
= hidden_field :item, :id , { value: @item.id, id: 'item' }
.spacer
.container
  .row
    .col-md-5.ml-auto.card.shop-card
      = image_tag @item.images.first.file, class: 'item-image'
      .row.ml-auto
        - @item.images.each do |image|
          .col-md-4
            = image_tag image.file, class: 'img-responsive img-thumbnail', id: 'enlarged'

    .col-md-1
    .col-md-3.mr-auto.card.shop-card
      %h2= @item.name
      %h6= number_to_currency(@item.price)
      %label Quantity:
      %input#qty{:type => "number", :value => "1", class: 'form-control'}
      %br
      .button.btn.btn-primary#addToCart Add to Cart